
BLENDER="blender.exe"
DIST=../dist

all : \
    $(DIST)/oil_rig.pnct \
    $(DIST)/oil_rig.scene \

$(DIST)/oil_rig.scene : oil_rig.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "oil_rig.blend:Main" "$(DIST)/oil_rig.scene"

$(DIST)/oil_rig.pnct : oil_rig.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "oil_rig.blend:Main" "$(DIST)/oil_rig.pnct" 
