
BLENDER="blender.exe"
DIST=../dist

all : \
    $(DIST)/test.pnct \
    $(DIST)/test.scene \

$(DIST)/test.scene : physics_test.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "physics_test.blend:Main" "$(DIST)/test.scene"

$(DIST)/test.pnct : physics_test.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "physics_test.blend:Main" "$(DIST)/test.pnct" 
